splunk/stef

benchmarks/go.mod, go/grpc/go.mod, go/otel/go.mod, go/pdata/go.mod, otelcol/go.mod
I have run the command make prepver VERSION=v0.0.1 from https://github.com/splunk/stef/pull/14
=> Prepare version v0.0.1

README.md, makefile
See README.md for how to use.
This is stacked on top of https://github.com/splunk/stef/pull/14
=> Add makefile target releasever

benchmarks/benchmarks_test.go, benchmarks/makefile, benchmarks/readwrite_test.go
The benchmarks github action is needed to prevent regressions to STEF performance. It is sufficient to run only STEF benchmarks for this. This will significantly speedup the PR builds.
=> Run only STEF benchmarks on github

benchmarks/go.mod, go/grpc/go.mod, go/otel/go.mod, go/pdata/go.mod, go/pkg/go.mod, otelcol/go.mod, stefgen/go.mod, stefgen/go.sum
This is to match Go version for Otelcol.
=> Downgrade to Go 1.22

benchmarks/go.mod, go/grpc/go.mod, go/otel/go.mod, go/pdata/go.mod, otelcol/go.mod
Run `make prepver VERSION=v0.0.2`.
=> Prepare v0.0.2 release

README.md, benchmarks/benchmarks_test.go, benchmarks/charts.go, benchmarks/encodings/metric_encoding.go, benchmarks/encodings/otlp/otlp.go, benchmarks/encodings/parquet/parquet.go, benchmarks/encodings/stef/stef.go, benchmarks/go.mod, benchmarks/go.sum, benchmarks/makefile, benchmarks/results/benchmarks.html, benchmarks/size_test.go
Running `make update-charts` in the benchmarks directory will now update results/benchmarks.html.
The output is visualized as bar charts.
=> Publish some benchmark results as HTML page

benchmarks/cmd/stefbench/main.go, go/otel/oteltef/metricswriter.go, go/otel/oteltef/spanswriter.go, go/pkg/basereader.go, go/pkg/header.go, go/pkg/writeropts.go, stefgen/templates/writer.go.tmpl
Resolves https://github.com/splunk/stef/issues/12
We may want to later add it to the UserData var header, but it definitely does not belong to the fixed Header.
=> Remove TimestampMultiplier from Header

go/otel/manual_test.go, go/otel/oteltef/attributes.go, go/otel/oteltef/envelopeattributes.go, go/otel/oteltef/keyvaluelist.go, stef-spec/specification.md, stefgen/templates/multimap.go.tmpl
We always use full encoding for Multimaps with more than 62 kv pairs.
Resolves https://github.com/splunk/stef/issues/6
=> Correctly handle Multimap with more than 62 kv pairs

go/grpc/client.go, otelcol/cmd/stefmockserver/main.go
Mock server previously could forget to send ACK on the last record received if not enough time passed since the last ACK.
Refactored the code make sure ACK is always sent, at approximately 100ms intervals, so ACK is sent at most 100 ms since the record is received.
Mock server can be used for testing the STEF exporter in Otel Collector.
=> Fix mock server to always send ACK

benchmarks/charts.go, benchmarks/makefile
This prevents touching benchmarks.html file when we are just running the benchmarks and tests.
=> Don't update benchmarks.html unless explictly requested

go/grpc/client.go, go/otel/grpc_test.go, go/otel/manual_test.go, go/otel/oteltef/dicts.go, go/otel/oteltef/metric.go, go/otel/oteltef/metricsreader.go, go/otel/oteltef/resource.go, go/otel/oteltef/scope.go, go/otel/oteltef/spansreader.go, go/pkg/basereader.go, go/pkg/encoders/string.go, go/pkg/writeropts.go, stefgen/templates/dicts.go.tmpl, stefgen/templates/reader.go.tmpl, stefgen/templates/struct.go.tmpl
We previously only had Writer setting the reset flag but Reader was ignoring it. Now the Reader also
correctly resets the dictionaries when it encounters the RestartDictionaries frame flag.
=> Implement dictionary reset on the Reader side

go/otel/oteltef/anyvalue.go, go/otel/oteltef/anyvaluearray.go, go/otel/oteltef/dicts.go, go/otel/oteltef/eventarray.go, go/otel/oteltef/exemplararray.go, go/otel/oteltef/exemplarvalue.go, go/otel/oteltef/float64array.go, go/otel/oteltef/int64array.go, go/otel/oteltef/linkarray.go, go/otel/oteltef/metricsreader.go, go/otel/oteltef/metricswriter.go, go/otel/oteltef/metricswriter_test.go, go/otel/oteltef/pointvalue.go, go/otel/oteltef/spansreader.go, go/otel/oteltef/spanswriter.go, go/otel/oteltef/spanswriter_test.go, go/pkg/frameflags.go, go/pkg/writeropts.go, stef-spec/specification.md, stefgen/templates/array.go.tmpl, stefgen/templates/dicts.go.tmpl, stefgen/templates/oneof.go.tmpl, stefgen/templates/reader.go.tmpl, stefgen/templates/writer.go.tmpl, stefgen/templates/writer_test.go.tmpl
Fixes https://github.com/splunk/stef/issues/47
Previously the flags were joint and incorrectly implemented. The writers previously always reset dictionaries and encoders at the same time, while readers only reset the dictionaries.
Now the flags are separate and each indicates the resetting of either dictionaries or codecs. The writers and readers correctly implement each flag.
Enabled previously disabled randomized write/read tests, which were failing because of incorrect implementation. Also added a few more randomized tests for other combinations of write options.
There is no performance impact for this change:
```
│     main     │                new                │
│    sec/op    │   sec/op     vs base              │
SerializeNative/STEF/none-10      3.952m ± 23%   4.030m ± 4%       ~ …
```
=> Separate RestartDictionaries and RestartCodecs frame flags

benchmarks/benchmarks_test.go, benchmarks/cmd/stats/main.go, benchmarks/cmd/stefbench/main.go, benchmarks/correctness_test.go, benchmarks/encodings/stef/stef.go, benchmarks/encodings/stef/stefs.go, benchmarks/encodings/stef/stefu.go, benchmarks/readwrite_test.go, benchmarks/size_test.go, go/otel/grpc_test.go, go/otel/manual_test.go, go/otel/oteltef/metricsreader.go, go/otel/oteltef/metricswriter_test.go, go/otel/oteltef/spansreader.go, go/otel/oteltef/spanswriter_test.go, go/pdata/metrics/pict_test.go, go/pdata/metrics/stef2otlp.go, go/pdata/metrics/stef2sortedtree.go, go/pkg/readopts.go, otelcol/cmd/stefmockserver/main.go, stefgen/templates/reader.go.tmpl, stefgen/templates/writer_test.go.tmpl
The API was inconsistent with Writer.Write() and was error-prone.
The new API is consistent with Writer.Write(). Both Writer.Write() and Reader.Read() now work with a Record that is an exporter field in the Writer/Reader struct. This makes it obvious that the Record is owned by the struct. Previously it was not clear if the pointer to the record returned by Reader.Read() was owned by the caller and could be modified and what it's lifetime was. Now it is more intuitively clear that the caller does not own the record and should not touch it and that the next Read() operation is going to overwrite it.
Also added pkg.ReadOptions to support reading options. The struct does not have any options yet, but options are coming in a future PR.
This is stacked on top of …
=> Refactor Reader.Read API

go/pkg/idl/lexer.go, go/pkg/idl/parser.go, go/pkg/idl/parser_test.go, go/pkg/idl/testdata/example.stef, go/pkg/schema/schema.go
It is now possible to declare enums in the IDL. We will use the enums in a future PR to generate enum code.
Contributes to https://github.com/splunk/stef/issues/51
=> Add enum to IDL and Schema

go/otel/manual_test.go, go/otel/oteltef/anyvalue.go, go/otel/oteltef/exemplarvalue.go, go/otel/oteltef/pointvalue.go, stefgen/templates/go/oneof.go.tmpl
Fixes https://github.com/splunk/stef/issues/86
When the new version of the schema adds a field to oneof and the type of the field is a new struct that is not present in the old version of the schema the initialization of the Reader fails since the decoder tries to find the new struct by the name in the old schema and fails. Instead of failing the Reader must skip the new struct and skip initializing its decoder.
=> Correctly handle reading STEF with old schema missing a struct

.github/workflows/benchmark.yml
See failure at https://github.com/splunk/stef/actions/runs/16060267344/job/45324418382?pr=104
Resolves 'Resource not accessible by integration' error when posting benchmark results as PR comments. The workflow now explicitly grants pull-requests:write permission to allow commenting on PRs from forks.
=> Fix benchmark workflow in github action

go/pdata/metrics/internal/baseotlptostef.go, go/pdata/metrics/internal/basesteftotolp.go
The equivalent in STEF does not require an enum
since it can be idiomatically expressed as the
None value of PointValue oneof.
Resolves https://github.com/splunk/stef/issues/70
=> Support NO_RECORDED_VALUE of DataPointFlags

docs/index.html, docs/sdl.html, docs/stefgen.html
Fix minor typos and inconsistencies
=> Cleanup docs

stefgen/generator/testdata/struct_recurse_reuse.stef
Closes https://github.com/splunk/stef/issues/94
Verifies that the bug we had in the past is fixed. I check column assignment manually and all tests also pass. There is nothing else to fix.
=> Add test case to verify column reuse

benchmarks/benchmarks_test.go, benchmarks/charts.go, benchmarks/size_test.go, docs/benchmarks.html, examples/jsonl/json2stef_test.go, examples/profile/pprof2stef_test.go
This adds zstd sizes to Profile and JSONL examples:
```
File --> Size in bytes         | JSON   | Protobuf       | STEF           | JSONZ  | ProtoZ | stefz
currencies_historical          |   4197 |   4393 (1.05x) |   1082 (0.26x) |    756 |   1105 |    782
macosx_releases                |   2449 |   2604 (1.06x) |    935 (0.38x) |    523 |    766 |    596
programming_languages_keywords |  10681 |  11912 (1.12x) |   8225 (0.77x) |   3746 |   5074 |   4053
File                 | pprof  | stef   | pprofz | stefz
deser_stef.prof      |  83343 |  83768 |  33326 |  29424 (1.005x/0.883x)
otelcol_otlp.prof    |  31864 |  38859 |  13054 |   9215 (1.220x/0.706x)
wsstreamasync.prof   |  92996 | 128295 |  29093 |  28150 (1.380x/0.968x)
```
Also makes zstd CPU times visible as a stack bar chart in …
=> Improve benchmark outputs to make zstd time/size more prominent

stef-spec/specification.md
The spec for Struct type was not correctly updated to reflect the changes made in https://github.com/splunk/stef/pull/124
This now fixes the spec.
=> Fix Struct spec to match the recent codec changes
